{% set name = "aicspylibczi" %}
{% set version = "3.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/aicspylibczi-{{ version }}.tar.gz
  sha256: 435d1544421cacc05838aa31afaade85da0972bd3638bfe008fae6e023248ad0

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake >=3.18
    - ninja
  host:
    - python
    - setuptools >=42
    - pytest-runner
    - pip
  run:
    - python
    - numpy >=1.14.1

test:
  imports:
    - aicspylibczi
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/AllenCellModeling/aicspylibczi
  summary: A python module and a python extension for Zeiss (CZI/ZISRAW) microscopy files.
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - multimeric
